name: Sauvegarde quotidienne de la base de données

on:
  schedule:
    - cron: '0 3 * * *' # tous les jours à 03h00 UTC (~4h/5h du matin au Togo)
  workflow_dispatch: # permet de lancer la sauvegarde manuellement depuis l'onglet Actions, pour tester

jobs:
  backup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backup
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Lancer la sauvegarde vers Google Drive
        env:
          MONGO_URI: ${{mongodb+srv://unifood_admin:UNIFOOD1234@cluster0.r9wqbtf.mongodb.net/unifood_maintenance?retryWrites=true&w=majority }}
          GOOGLE_CLIENT_ID: ${{305204329498-mkmvp8t6vs09lchoa1r57atkptklfe9j.apps.googleusercontent.com }}
          GOOGLE_CLIENT_SECRET: ${{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 }}
          GOOGLE_REFRESH_TOKEN: ${{1//09xJdlZnT822nCgYIARAAGAkSNwF-L9Ire26PsNob64sDogXv9QVyOtImOBbVVuasVuoPMCor4JdU58pOK7Vy_nLmf5KUfdlUoE8 }}
          GDRIVE_FOLDER_ID: ${{1JXHf749xed-1yJUhijjElcxK-m5hELJV }}
        run: npm run backup
